# Generated by Django 4.0.6 on 2022-07-26 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videoclub', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='duration',
            field=models.PositiveIntegerField(help_text='Duración en minutos', verbose_name='Duracion'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='year',
            field=models.PositiveIntegerField(help_text='Año de lanzamiento', verbose_name='Año'),
        ),
    ]
